-- AlterTable
ALTER TABLE "Servant" ADD COLUMN IF NOT EXISTS "offersSession" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Servant" ADD COLUMN IF NOT EXISTS "offersMonthly" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Servant" ADD COLUMN IF NOT EXISTS "weekOffDays" TEXT;
ALTER TABLE "Servant" ADD COLUMN IF NOT EXISTS "hoursPerDay" DOUBLE PRECISION;
ALTER TABLE "Servant" ADD COLUMN IF NOT EXISTS "availabilityNotes" TEXT;
