import { StyleSheet } from 'react-native';
import { Stitch } from '@/theme/stitch';

export const locationPickerStyles = StyleSheet.create({
  wrap: { marginBottom: 16 },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: Stitch.colors.onSurfaceVariant,
    marginBottom: 8,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Stitch.colors.surfaceLow,
    borderRadius: Stitch.radius.md,
    paddingHorizontal: 12,
    minHeight: 48,
    gap: 8,
  },
  input: { flex: 1, fontSize: 16, color: Stitch.colors.onBackground },
  suggestions: {
    marginTop: 8,
    backgroundColor: Stitch.colors.surface,
    borderRadius: Stitch.radius.md,
    borderWidth: 1,
    borderColor: Stitch.colors.outlineVariant,
    maxHeight: 180,
    overflow: 'hidden',
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Stitch.colors.outlineVariant,
  },
  suggestionText: { flex: 1 },
  suggestionMain: { fontWeight: '600', color: Stitch.colors.onBackground },
  suggestionSub: { fontSize: 12, color: Stitch.colors.onSurfaceVariant, marginTop: 2 },
  mapWrap: {
    marginTop: 12,
    borderRadius: Stitch.radius.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Stitch.colors.outlineVariant,
  },
  webHint: {
    marginTop: 12,
    padding: 16,
    borderRadius: Stitch.radius.lg,
    backgroundColor: Stitch.colors.surfaceContainer,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  webHintText: { color: Stitch.colors.onSurfaceVariant, lineHeight: 20, textAlign: 'center' },
  gpsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: Stitch.radius.pill,
    backgroundColor: Stitch.colors.primaryFixed,
  },
  gpsText: { color: Stitch.colors.primary, fontWeight: '600', fontSize: 13 },
  selected: { marginTop: 10, color: Stitch.colors.onBackground, lineHeight: 20 },
  hint: { marginTop: 10, color: Stitch.colors.onSurfaceVariant, fontSize: 13 },
});
